steps:

  - id: 'Instalando dependencias'
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'app']

  - id: 'Rodando os Testes Unitários'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v','app']

  - id: 'Build the container imagem'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '--tag', 'gcr.io/$PROJECT_ID/go-hpa', '.', '--no-cache']

  - id: 'Push the container image to Container Registry'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/go-hpa']

  - id: 'Deploy container image to Cloud Run'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'go-hpa', '--image', 'gcr.io/$PROJECT_ID/go-hpa', '--region', 'us-central1','--platform', 'managed', '--quiet']

  - id: 'Add iam Policy'
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'services', 'add-iam-policy-binding', 'go-hpa', '--member', 'gcr.io/$PROJECT_ID/go-hpa', '--region', 'us-central1','--platform', 'allUsers', '--role', 'roles/run.invoker']

images:
  - gcr.io/${PROJECT_ID}/go-hpa:${COMMIT_SHA}


### Setting up continuous deployment with Cloud Build
# steps:
#   # build the container image
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/[SERVICE-NAME]', '.']
#   # push the container image to Container Registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/$PROJECT_ID/[SERVICE-NAME]']
#   # Deploy container image to Cloud Run
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['beta', 'run', 'deploy', '[SERVICE-NAME]', '--image', 'gcr.io/$PROJECT_ID/[SERVICE-NAME]', '--region', '[REGION]','--platform', '[PLATFORM]', '--quiet']
# images:
# - gcr.io/$PROJECT_ID/[SERVICE-NAME]

#   - id: build-test-image
#     name: gcr.io/cloud-builders/docker
#     entrypoint: bash
#     args:
#       - -c
#       - |
#         docker image build --target build --tag greeting:test .
#
#   - id: run-tests
#     name: gcr.io/cloud-builders/docker
#     entrypoint: bash
#     args:
#       - -c
#       - |
#         docker container run greeting:test go test
#
#   - id: build-app
#     name: gcr.io/cloud-builders/docker
#     entrypoint: bash
#     args:
#       - -c
#       - |
#         docker image build --tag gcr.io/${PROJECT_ID}/greeting:${COMMIT_SHA} .
#
# images:
#   - gcr.io/${PROJECT_ID}/greeting:${COMMIT_SHA}
