FROM golang:1.11-alpine AS build

RUN apk add --update --no-cache gcc git build-base

WORKDIR /go/src/app
ADD ./src/app /go/src/app

RUN CGO_ENABLED=0 go build -o /bin/demo

FROM scratch
COPY --from=build /bin/demo /bin/demo

EXPOSE 8000

WORKDIR /go/src/app
ENTRYPOINT ["/bin/demo"]
