version: '3'
services:
  codeeducation:
    container_name: golang
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
